all:	red_object_tracking

red_object_tracking: red_object_tracking.cpp
	g++ red_object_tracking.cpp -o red_object_tracking -L/usr/local/lib -I/home/simon/code/cvblob/cvBlob -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lQt5Core -lQt5Gui -lQt5Widgets -lQt5Test -lQt5Concurrent -lQt5OpenGL -lpng -lz -ltiff -ljasper -ljpeg -lImath -lIlmImf -lIex -lHalf -lIlmThread -ldc1394 -lavcodec -lavformat -lavutil -lswscale -lavresample -ldl -lm -lpthread -lrt -lGLU -lGL -lSM -lICE -lX11 -lXext -lcvblob

